language: node_js
os:
    - windows
    - osx
    - linux
node_js:
    - 12
    - 10
    - 8

env:
    global:
        COVERALLS_PARALLEL: true

after_success: nyc report --reporter=text-lcov | coveralls
